Repository FACG5/BounceBack, pull requests merged in 2018-12, with the labels that each got.

#242 Refactoring
  src/client/src/components/pages/courses/addCourses/staticData.js
  src/client/src/components/pages/managers/managerDetails/staticData.js
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/client/src/components/pages/participants/participantDetails/staticData.js
  src/client/src/components/pages/participants/prisonDetails/staticData.js
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/server/database/models/participant.js
Labels: Approved, refactoring

#248 Validation
  package.json
  src/client/src/components/abstract/input/index.jsx
  src/client/src/components/pages/courses/addCourses/staticData.js
  src/client/src/components/pages/managers/addManager/staticData.js
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/client/src/helpers/index.js
  src/server/database/models/participant.js
Labels: waiting-review

#252 Enhancements
  src/client/src/components/pages/managers/addManager/staticData.js
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/client/src/components/pages/participants/prisonDetails/index.jsx
  src/client/src/components/pages/participants/prisonDetails/staticData.js
  src/client/src/helpers/index.js
  src/server/database/models/participant.js
Labels: waiting-review

#256 Upload file
  package.json
  src/client/src/components/pages/participants/addParticipant/index.jsx
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/server/CVs/.gitignore
  src/server/app.js
  src/server/controllers/participants.js
Labels: awaiting-review

#257 Handling errors
  src/client/src/components/pages/participants/addParticipantCourse/index.jsx
  src/client/src/components/pages/participants/addParticipantDate/index.jsx
  src/client/src/components/pages/participants/addParticipantPastoral/index.jsx
  src/client/src/components/pages/workers/addWorkers/staticData.js
Labels: waiting-review

#261 Enhancement
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/client/src/components/pages/participants/participantDetails/staticData.js
Labels: Approved

#262 Enhancement
  src/client/src/components/pages/dashboard/index.jsx
  src/server/controllers/getCount.js
Labels: waiting-review

#263 Refactoring1
  src/client/src/components/pages/dashboard/index.jsx
  src/client/src/components/pages/workers/viewWorkers/index.jsx
Labels: Approved

#271 fixing
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/client/src/components/pages/participants/viewParticipants/style.css
Labels: waiting-review

#272 Refactoring
  src/client/src/components/pages/participants/addParticipantCourse/staticData.js
  src/client/src/components/pages/participants/addParticipantPastoral/staticData.js
Labels: Approved, Done

#277 edit validation
  src/client/src/components/pages/managers/addManager/staticData.js
  src/client/src/components/pages/participants/addParticipant/staticData.js
Labels: Approved

#279 Fixing
  src/client/src/components/pages/participants/participantDetails/index.jsx
  src/client/src/components/pages/participants/prisonerDetails/staticData.js
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/server/controllers/index.js
  src/server/controllers/participants.js
Labels: Approved

#278 F-E validation
  src/client/src/components/pages/courses/courseDetails/index.jsx
  src/client/src/components/pages/courses/courseDetails/staticData.js
  src/client/src/components/pages/courses/pastoral/index.jsx
  src/client/src/components/pages/managers/addManager/index.jsx
  src/client/src/components/pages/managers/managerDetails/index.jsx
  src/client/src/components/pages/managers/managerDetails/staticData.js
  src/client/src/components/pages/participants/participantCourseDetails/index.jsx
  src/client/src/components/pages/participants/participantCourseDetails/staticData.js
  src/client/src/components/pages/participants/participantCourses/index.jsx
  src/client/src/components/pages/participants/participantDateDetails/index.jsx
  src/client/src/components/pages/participants/participantDetails/index.jsx
  src/client/src/components/pages/participants/participantDetails/staticData.js
  src/client/src/components/pages/participants/participantPasroralDetails/index.jsx
  src/client/src/components/pages/participants/participantPasroralDetails/staticData.js
  src/client/src/components/pages/participants/prisonerDetails/index.jsx
  src/client/src/components/pages/participants/prisonerDetails/staticData.js
  src/client/src/components/pages/workers/workerDetails/index.jsx
  src/client/src/components/pages/workers/workerDetails/staticData.js
Labels: Approved

#280 edits
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/server/controllers/courses.js
Labels: Approved

#282 Lastfix
  src/client/src/components/pages/courses/courseDetails/index.jsx
  src/client/src/components/pages/courses/pastoral/index.jsx
  src/client/src/components/pages/participants/participantDetails/index.jsx
  src/client/src/components/pages/workers/workerDetails/index.jsx
Labels: Approved
