Repository FACG5/BounceBack, pull requests merged in 2018-11, with the labels that each got.

#38 File structure
  .gitignore
  package-lock.json
  package.json
  src/client/public/favicon.ico
  src/client/public/index.html
  src/client/src/components/App.js
  src/client/src/index.js
  src/client/src/serviceWorker.js
  src/server/app.js
  src/server/controllers/index.js
  src/server/index.js
Labels: File-Structure, waiting-review

#58 File structure
  src/client/.gitignore
  src/client/package.json
Labels: File-Structure, waiting-review

#61 Button component
  src/client/src/components/abstract/button/index.css
  src/client/src/components/abstract/button/index.jsx
Labels: Components, waiting-review

#62 Statistics component
  src/client/src/components/abstract/statistics/index.jsx
  src/client/src/components/abstract/statistics/style.css
Labels: waiting-review

#64 Header footer components
  src/client/src/components/abstract/Table/index.jsx
  src/client/src/components/abstract/footer/index.jsx
  src/client/src/components/abstract/footer/style.css
  src/client/src/components/abstract/header/index.jsx
  src/client/src/components/abstract/header/style.css
Labels: Components, request-changes

#63 Input Component
  src/client/src/components/abstract/input/index.css
  src/client/src/components/abstract/input/index.jsx
Labels: Components

#68 Input components
  src/client/src/components/abstract/dropdown/index.jsx
  src/client/src/components/abstract/dropdown/style.css
Labels: waiting-review

#69 Textarea component
  src/client/src/components/abstract/textarea/index.css
  src/client/src/components/abstract/textarea/index.jsx
Labels: Components, waiting-review

#76 View participant page
  package.json
  src/client/package.json
  src/client/src/components/App.css
  src/client/src/components/App.js
  src/client/src/components/abstract/Table/index.jsx
  src/client/src/components/abstract/Table/style.css
  src/client/src/components/abstract/dropdown/index.jsx
  src/client/src/components/abstract/header/index.jsx
  src/client/src/components/abstract/header/style.css
  src/client/src/components/abstract/input/index.jsx
  src/client/src/components/abstract/sidebar/index.jsx
  src/client/src/components/abstract/sidebar/sidebarTitles/index.jsx
  src/client/src/components/abstract/sidebar/style.css
  src/client/src/components/pages/viewParticipants/index.jsx
  src/client/src/components/pages/viewParticipants/style.css
Labels: Front-End, waiting-review

#78 Add participant page
  src/client/src/components/App.js
  src/client/src/components/abstract/Form/index.css
  src/client/src/components/abstract/Form/index.jsx
  src/client/src/components/pages/participants/addParticipant/index.css
  src/client/src/components/pages/participants/addParticipant/index.jsx
  src/client/src/components/pages/participants/addParticipant/staticData.js
Labels: waiting-merge

#79 Dashbourd
  src/client/src/components/App.js
  src/client/src/components/abstract/footer/style.css
  src/client/src/components/abstract/statistics/index.jsx
  src/client/src/components/abstract/statistics/style.css
  src/client/src/components/pages/dashboard/index.jsx
  src/client/src/components/pages/dashboard/style.css
Labels: waiting-merge

#80 Course details page
  src/client/src/components/App.js
  src/client/src/components/abstract/Table/style.css
  src/client/src/components/abstract/sidebar/sidebarTitles/index.jsx
  src/client/src/components/pages/dates/index.jsx
  src/client/src/components/pages/viewCourses/index.jsx
  src/client/src/components/pages/viewManagers/index.jsx
Labels: request-changes

#81 view Managers page
  src/client/src/components/App.js
  src/client/src/components/abstract/Table/index.jsx
  src/client/src/components/abstract/Table/style.css
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/client/src/components/pages/participants/viewParticipants/style.css
  src/client/src/components/pages/viewCourses/index.jsx
  src/client/src/components/pages/workers/viewWorkers/index.jsx
Labels: waiting-merge

#83 Result report
  src/client/src/components/App.js
  src/client/src/components/abstract/Table/index.jsx
  src/client/src/components/abstract/Table/style.css
  src/client/src/components/pages/reportResult/index.jsx
  src/client/src/components/pages/reportResult/style.css
  src/client/src/index.css
Labels: Done, waiting-merge

#85 Add workers
  src/client/src/components/App.js
  src/client/src/components/pages/courses/addCourses/index.jsx
  src/client/src/components/pages/managers/addManager/index.jsx
  src/client/src/components/pages/participants/addParticipant/index.jsx
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/client/src/components/pages/workers/addWorker/staticData.js
  src/client/src/components/pages/workers/addWorkers/index.jsx
  src/client/src/components/pages/workers/addWorkers/staticData.js
Labels: waiting-merge

#86 Edit static style
  src/client/src/components/abstract/dropdown/style.css
  src/client/src/components/abstract/footer/style.css
  src/client/src/components/abstract/input/index.css
  src/client/src/components/abstract/layout/Container/index.jsx
  src/client/src/components/abstract/layout/Container/style.css
  src/client/src/components/abstract/textarea/index.css
  src/client/src/components/pages/participants/addParticipant/staticData.js
Labels: waiting-merge

#87 Edit styling
  src/client/src/components/abstract/dropdown/style.css
  src/client/src/components/abstract/header/style.css
  src/client/src/components/abstract/input/index.css
  src/client/src/components/abstract/textarea/index.css
  src/client/src/components/pages/courses/addCourses/index.jsx
  src/client/src/components/pages/courses/addCourses/staticData.js
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/managers/addManager/staticData.js
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/client/src/components/pages/report/index.jsx
  src/client/src/components/pages/report/style.css
  src/client/src/components/pages/reportResult/index.jsx
  src/client/src/components/pages/workers/addWorkers/staticData.js
  src/client/src/components/pages/workers/viewWorkers/index.jsx
  src/client/src/index.css
Labels: Done, waiting-merge

#88 Participant details
  src/client/src/components/App.js
  src/client/src/components/abstract/Form/index.jsx
  src/client/src/components/pages/courses/addCourses/staticData.js
  src/client/src/components/pages/dates/index.jsx
  src/client/src/components/pages/managers/addManager/staticData.js
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/client/src/components/pages/participants/participantCourses/index.jsx
  src/client/src/components/pages/participants/participantDates/index.jsx
  src/client/src/components/pages/participants/participantDetails/index.jsx
  src/client/src/components/pages/participants/participantDetails/staticData.js
  src/client/src/components/pages/workers/addWorkers/staticData.js
Labels: waiting-merge

#96 General edits
  src/client/src/components/App.js
  src/client/src/components/abstract/Form/index.jsx
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/managers/addManager/staticData.js
  src/client/src/components/pages/participants/addParticipantCourse/index.jsx
  src/client/src/components/pages/participants/addParticipantCourse/staticData.js
  src/client/src/components/pages/participants/addParticipantDate/index.jsx
  src/client/src/components/pages/participants/addParticipantDate/staticData.js
  src/client/src/components/pages/participants/participantCourseDetails/index.jsx
  src/client/src/components/pages/participants/participantCourseDetails/staticData.js
  src/client/src/components/pages/participants/participantDateDetails/index.jsx
  src/client/src/components/pages/participants/participantDateDetails/staticData.js
  src/client/src/components/pages/participants/participantDetails/staticData.js
Labels: waiting-merge

#92 Manager details
  src/client/src/components/App.js
  src/client/src/components/pages/managers/managerDetails/index.jsx
  src/client/src/components/pages/managers/managerDetails/staticData.js
Labels: Front-End, waiting-merge

#91 Course details
  src/client/src/components/App.js
  src/client/src/components/pages/courses/courseDetails/index.jsx
  src/client/src/components/pages/courses/courseDetails/staticData.js
Labels: Front-End, waiting-merge

#93 Worker details
  src/client/src/components/App.js
  src/client/src/components/pages/workers/workerDetails/index.jsx
  src/client/src/components/pages/workers/workerDetails/staticData.js
Labels: Front-End, waiting-merge

#99 Editing
  src/client/src/components/pages/participants/participantCourses/index.jsx
  src/client/src/components/pages/participants/participantDates/index.jsx
Labels: waiting-review

#100 Editing
  src/client/src/components/pages/participants/participantDetails/index.jsx
  src/client/src/components/pages/participants/participantDetails/staticData.js
Labels: waiting-review

#101 Editing
  src/client/src/components/pages/participants/addParticipantDate/staticData.js
  src/client/src/components/pages/participants/participantDates/index.jsx
  src/client/src/components/pages/participants/prisonDetails/staticData.js
Labels: Approved, waiting-merge

#106 travis file
  .travis.yml
  src/client/package.json
  src/client/src/components/abstract/Form/index.jsx
  src/client/src/components/pages/courses/addCourses/index.jsx
  src/client/src/components/pages/workers/addWorkers/staticData.js
Labels: Approved, Done

#135 Database
  .gitignore
  config.js
  package.json
  src/server/database/config/connection.js
  src/server/database/models/course.js
  src/server/database/models/dates.js
  src/server/database/models/index.js
  src/server/database/models/participant.js
  src/server/database/models/participantCourses.js
  src/server/database/models/prison.js
  src/server/database/models/staff.js
  src/server/database/models/worker.js
  src/server/index.js
Labels: waiting-review

#138 add staff model
  src/server/database/models/index.js
Labels: Approved, waiting-merge

#140 Overview
  package.json
  src/client/src/components/pages/dashboard/index.jsx
  src/server/controllers/getCount.js
  src/server/controllers/index.js
Labels: Approved, waiting-merge

#142 Workers
  src/client/src/components/pages/workers/viewWorkers/index.jsx
  src/server/controllers/index.js
  src/server/controllers/workers.js
Labels: Approved, waiting-merge

#145 Auth
  package.json
  src/client/src/components/App.js
  src/client/src/components/abstract/sidebar/sidebarLinks/index.jsx
  src/client/src/components/abstract/sidebar/sidebarLinks/removeCookies.js
  src/client/src/components/abstract/sidebar/sidebarLinks/style.css
  src/client/src/components/context/index.js
  src/client/src/components/pages/login/index.jsx
  src/client/src/index.js
  src/server/app.js
  src/server/controllers/index.js
  src/server/controllers/login.js
  src/server/helpers/checkPassword.js
  src/server/helpers/getStaff.js
  src/server/helpers/makeToken.js
  src/server/index.js
Labels: Approved, waiting-merge

#148 Managers
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/client/src/components/pages/workers/viewWorkers/index.jsx
  src/server/controllers/index.js
  src/server/controllers/managers.js
Labels: Approved, waiting-merge

#143 View participants
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/server/controllers/index.js
  src/server/controllers/participants.js
Labels: Approved, waiting-merge

#144 Toggle Sidebar
  src/client/src/components/abstract/sidebar/sidebarLinks/index.jsx
  src/client/src/components/abstract/sidebar/sidebarLinks/style.css
  src/client/src/components/abstract/sidebar/sidebarTitles/index.jsx
  src/client/src/components/abstract/sidebar/sidebarTitles/style.css
Labels: Approved, waiting-merge

#151 edit staff table
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/client/src/components/pages/workers/viewWorkers/index.jsx
  src/client/src/index.css
  src/server/controllers/index.js
  src/server/database/models/staff.js
  src/server/index.js
Labels: Approved, waiting-merge

#154 Sweet allert
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/client/src/components/pages/workers/viewWorkers/index.jsx
  src/client/src/index.css
Labels: Approved, Done, waiting-merge

#156 remove force: true in sync
  src/server/index.js
Labels: waiting-review

#160 Search course
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/server/controllers/courses.js
  src/server/controllers/index.js
Labels: Approved, waiting-merge

#161 Search worker
  src/client/src/components/pages/workers/viewWorkers/index.jsx
  src/server/controllers/index.js
  src/server/controllers/workers.js
Labels: Approved, waiting-merge

#158 edit table
  src/client/src/components/abstract/Table/style.css
Labels: Approved, waiting-merge

#159 Participant search
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/server/controllers/index.js
  src/server/controllers/participants.js
Labels: Approved, waiting-merge

#165 course details
  src/client/src/components/App.js
  src/client/src/components/pages/courses/courseDetails/index.jsx
  src/client/src/components/pages/courses/courseDetails/staticData.js
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/server/controllers/courses.js
  src/server/controllers/index.js
Labels: Approved, waiting-merge

#166 Edit routes
  src/client/src/components/pages/courses/courseDetails/index.jsx
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/dashboard/index.jsx
  src/client/src/components/pages/login/index.jsx
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/client/src/components/pages/workers/viewWorkers/index.jsx
  src/server/app.js
Labels: Approved, waiting-merge

#169 Auth
  src/client/src/components/App.js
  src/client/src/components/abstract/HOC/contextHoc.js
  src/client/src/components/abstract/sidebar/sidebarLinks/index.jsx
  src/client/src/components/pages/login/index.jsx
Labels: Approved, waiting-merge

#170 Details worker
  src/client/src/components/pages/workers/viewWorkers/index.jsx
  src/client/src/components/pages/workers/workerDetails/index.jsx
  src/client/src/components/pages/workers/workerDetails/staticData.js
  src/server/controllers/index.js
  src/server/controllers/workers.js
Labels: Approved, waiting-merge

#171 Detail manager
  src/client/src/components/pages/managers/managerDetails/index.jsx
  src/client/src/components/pages/managers/managerDetails/staticData.js
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/server/controllers/index.js
  src/server/controllers/managers.js
Labels: Approved, waiting-merge

#173 solve warning problem
  src/client/public/index.html
  src/client/src/components/abstract/Form/index.jsx
  src/client/src/components/abstract/input/index.jsx
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/client/src/components/pages/participants/participantDetails/index.jsx
  src/client/src/components/pages/participants/participantDetails/staticData.js
  src/server/controllers/participants.js
Labels: Approved, waiting-merge

#172 Add participant
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/participants/addParticipant/index.jsx
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/server/controllers/index.js
  src/server/controllers/participants.js
Labels: Approved, waiting solve conflicts

#174 Error pages
  src/client/src/components/App.js
  src/client/src/components/context/index.js
  src/client/src/components/pages/errors/index.jsx
  src/client/src/components/pages/errors/style.css
  src/client/src/components/pages/login/index.jsx
Labels: waiting-review

#175 add will mount function
  src/client/src/components/pages/dashboard/index.jsx
Labels: Approved, waiting-merge

#179 Participant dates
  src/client/src/components/App.js
  src/client/src/components/pages/participants/participantDates/index.jsx
  src/client/src/components/pages/participants/participantDetails/index.jsx
  src/client/src/components/pages/participants/participantDetails/staticData.js
  src/client/src/components/pages/participants/participantDetails/style.css
  src/server/controllers/index.js
  src/server/controllers/participants.js
Labels: Approved, waiting-merge

#177 Add course
  src/client/src/components/pages/courses/addCourses/index.jsx
  src/client/src/components/pages/courses/addCourses/staticData.js
  src/client/src/components/pages/dashboard/index.jsx
  src/client/src/components/pages/participants/addParticipant/index.jsx
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/server/controllers/courses.js
  src/server/controllers/index.js
Labels: Approved, waiting-merge

#185 Edit details page
  src/client/src/components/pages/participants/participantDetails/index.jsx
  src/client/src/components/pages/participants/participantDetails/staticData.js
  src/client/src/components/pages/participants/participantDetails/style.css
Labels: Approved, waiting-merge

#189 Dates details
  src/client/src/components/pages/participants/participantDateDetails/index.jsx
  src/client/src/components/pages/participants/participantDateDetails/staticData.js
  src/server/controllers/index.js
  src/server/controllers/participants.js
Labels: Approved, waiting-merge

#192 Eslint fixing
  package.json
  src/server/app.js
  src/server/controllers/courses.js
  src/server/controllers/getCount.js
  src/server/controllers/index.js
  src/server/controllers/login.js
  src/server/controllers/managers.js
  src/server/controllers/participants.js
  src/server/controllers/workers.js
  src/server/database/config/connection.js
  src/server/database/models/course.js
  src/server/database/models/dates.js
  src/server/database/models/index.js
  src/server/database/models/participant.js
  src/server/database/models/participantCourses.js
  src/server/database/models/prison.js
  src/server/database/models/staff.js
  src/server/database/models/worker.js
  src/server/helpers/checkPassword.js
  src/server/helpers/getStaff.js
  src/server/helpers/makeToken.js
  src/server/index.js
Labels: Approved, waiting-merge

#190 Updates
  src/client/src/components/pages/courses/courseDetails/index.jsx
  src/client/src/components/pages/managers/managerDetails/index.jsx
  src/client/src/components/pages/managers/managerDetails/staticData.js
  src/client/src/components/pages/workers/workerDetails/index.jsx
  src/server/controllers/courses.js
  src/server/controllers/index.js
  src/server/controllers/managers.js
  src/server/controllers/workers.js
Labels: Approved, waiting-merge

#193 Edit add participant
  src/client/src/components/App.js
  src/client/src/components/pages/participants/addParticipant/index.css
  src/client/src/components/pages/participants/addParticipant/index.jsx
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/server/controllers/participants.js
Labels: Approved, waiting-merge

#194 Auth
  src/client/src/components/pages/login/index.jsx
Labels: Approved, waiting-merge

#202 Add interventions
  src/client/src/components/pages/participants/addParticipantCourse/index.jsx
Labels: Approved, waiting-merge

#203 add a new enhancements
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/errors/index.jsx
  src/client/src/components/pages/errors/style.css
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/client/src/components/pages/participants/participantCourseDetails/staticData.js
  src/client/src/components/pages/participants/participantCourses/index.jsx
  src/client/src/components/pages/participants/participantDates/index.jsx
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/client/src/components/pages/workers/viewWorkers/index.jsx
Labels: waiting-review

#204 edit error page
  src/client/src/components/pages/errors/index.jsx
  src/client/src/components/pages/errors/style.css
Labels: Approved

#205 General edits
  src/client/src/components/pages/courses/addCourses/staticData.js
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/dashboard/index.jsx
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/client/src/components/pages/report/style.css
  src/client/src/components/pages/workers/viewWorkers/index.jsx
Labels: Approved, Done

#206 Edit participant courses table and views
  src/client/src/components/pages/participants/addParticipantCourse/staticData.js
  src/client/src/components/pages/participants/participantCourseDetails/staticData.js
  src/server/database/models/participantCourses.js
Labels: Approved, Done

#208 Pie chart Component
  package.json
  src/client/src/components/abstract/pieChart/index.css
  src/client/src/components/abstract/pieChart/index.jsx
  src/client/src/components/abstract/pieChart/logic.js
Labels: Approved, waiting-merge

#209 participants status charts
  src/client/src/components/pages/dashboard/index.jsx
  src/server/controllers/getCount.js
Labels: waiting-review

#210 Edit style
  src/client/src/components/abstract/Table/style.css
  src/client/src/components/abstract/sidebar/sidebarLinks/index.jsx
  src/client/src/components/pages/login/index.jsx
  src/client/src/components/pages/login/style.css
  src/client/src/components/pages/managers/addManager/staticData.js
  src/server/controllers/courses.js
Labels: waiting-review

#211 edit the style of pie chart
  src/client/src/components/abstract/pieChart/index.css
  src/client/src/components/pages/dashboard/index.jsx
Labels: enhancement, waiting-review

#212 Editions
  src/client/src/components/pages/courses/courseDetails/index.jsx
  src/client/src/components/pages/courses/courseDetails/staticData.js
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/dashboard/index.jsx
  src/client/src/components/pages/loading/index.css
  src/client/src/components/pages/loading/index.jsx
  src/client/src/components/pages/login/index.jsx
  src/client/src/components/pages/managers/managerDetails/index.jsx
  src/client/src/components/pages/managers/managerDetails/staticData.js
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/client/src/components/pages/participants/addParticipantCourse/index.jsx
  src/client/src/components/pages/participants/addParticipantDate/index.jsx
  src/client/src/components/pages/participants/participantCourseDetails/index.jsx
  src/client/src/components/pages/participants/participantCourseDetails/staticData.js
  src/client/src/components/pages/participants/participantCourses/index.jsx
  src/client/src/components/pages/participants/participantDateDetails/index.jsx
  src/client/src/components/pages/participants/participantDateDetails/staticData.js
  src/client/src/components/pages/participants/participantDates/index.jsx
  src/client/src/components/pages/participants/participantDetails/index.jsx
  src/client/src/components/pages/participants/participantDetails/staticData.js
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/client/src/components/pages/workers/viewWorkers/index.jsx
  src/client/src/components/pages/workers/workerDetails/index.jsx
  src/client/src/components/pages/workers/workerDetails/staticData.js
Labels: Approved, enhancement, waiting-merge

#218 Adding category to database
  src/client/src/components/abstract/sidebar/sidebarTitles/index.jsx
  src/client/src/components/pages/courses/addCourses/staticData.js
  src/client/src/components/pages/courses/pastoral/staticData.js
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/server/database/models/course.js
Labels: waiting-review

#220 Edit Add Course
  src/client/src/components/pages/courses/addCourses/index.jsx
Labels: Approved

#219 Auth
  src/client/src/components/App.js
  src/client/src/components/pages/login/index.jsx
  src/server/controllers/index.js
  src/server/controllers/login.js
  src/server/helpers/makeToken.js
  src/server/middleware/auth.js
Labels: Approved

#221 Charts
  src/client/src/components/abstract/pieChart/index.css
  src/client/src/components/abstract/sidebar/style.css
  src/client/src/components/pages/courses/courseDetails/index.jsx
  src/client/src/components/pages/courses/courseDetails/staticData.js
  src/client/src/components/pages/dashboard/index.jsx
  src/client/src/components/pages/participants/addParticipantCourse/index.jsx
  src/client/src/components/pages/participants/addParticipantCourse/staticData.js
  src/client/src/components/pages/participants/participantCourseDetails/staticData.js
  src/client/src/components/pages/participants/participantCourses/index.jsx
  src/client/src/index.css
  src/server/controllers/courses.js
  src/server/controllers/getCount.js
  src/server/controllers/index.js
  src/server/database/models/participantCourses.js
Labels: waiting-review

#222 Main chart
  src/client/src/components/abstract/pieChart/index.css
  src/client/src/components/abstract/pieChart/index.jsx
  src/client/src/components/abstract/pieChart/logic.js
  src/client/src/components/pages/dashboard/index.jsx
  src/client/src/components/pages/dashboard/style.css
  src/server/controllers/getCount.js
  src/server/database/models/participantCourses.js
Labels: Approved

#223 Edit functions
  src/client/src/components/abstract/pieChart/logic.js
  src/client/src/components/pages/dashboard/index.jsx
Labels: Approved, Done

#227 Auth
  src/client/src/components/App.js
  src/client/src/components/pages/login/index.jsx
  src/client/src/helpers/index.js
  src/server/controllers/login.js
Labels: Approved, urgent

#225 Fixing
  src/client/src/components/pages/dashboard/index.jsx
Labels: Approved

#226 edit places of two fields
  src/client/src/components/pages/participants/addParticipant/staticData.js
Labels: Approved

#229 UUID
  package.json
  src/client/src/components/abstract/Form/index.jsx
  src/client/src/components/abstract/Table/index.jsx
  src/client/src/components/abstract/dropdown/index.jsx
  src/client/src/components/abstract/pieChart/index.jsx
  src/client/src/components/pages/courses/courseDetails/index.jsx
Labels: Approved

#230 add index to select colors
  src/client/src/components/abstract/pieChart/index.jsx
Labels: Approved

#231 Edits
  src/client/src/components/App.js
  src/client/src/components/Routes/allComponents.js
  src/client/src/components/Routes/index.js
  src/client/src/components/abstract/Form/index.jsx
  src/client/src/components/abstract/pieChart/index.css
  src/client/src/components/abstract/pieChart/index.jsx
  src/client/src/helpers/index.js
  src/server/controllers/index.js
Labels: Approved

#232 Charts
  src/client/src/components/abstract/pieChart/index.css
  src/client/src/components/abstract/pieChart/index.jsx
  src/client/src/components/abstract/pieChart/logic.js
  src/client/src/components/pages/courses/courseDetails/index.jsx
  src/client/src/components/pages/dashboard/index.jsx
  src/client/src/components/pages/dashboard/style.css
  src/client/src/components/pages/participants/addParticipant/staticData.js
Labels: Approved, Done

#233 Enhancements
  src/client/src/components/abstract/pieChart/index.css
  src/client/src/components/abstract/pieChart/logic.js
  src/client/src/components/abstract/sidebar/sidebarTitles/index.jsx
  src/client/src/components/pages/dashboard/style.css
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/client/src/components/pages/participants/participantDetails/staticData.js
  src/client/src/components/pages/participants/viewParticipants/index.jsx
  src/server/controllers/participants.js
  src/server/database/models/participant.js
Labels: waiting-review

#234 Edits
  src/client/src/components/App.js
  src/client/src/components/abstract/Form/index.css
  src/client/src/components/abstract/Form/index.jsx
  src/client/src/components/abstract/button/index.jsx
  src/client/src/components/abstract/dropdown/index.jsx
  src/client/src/components/abstract/input/index.jsx
  src/client/src/components/abstract/sidebar/sidebarLinks/index.jsx
  src/client/src/components/abstract/sidebar/sidebarTitles/index.jsx
  src/client/src/components/abstract/textarea/index.jsx
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/managers/viewManagers/index.jsx
  src/client/src/components/pages/participants/addParticipant/index.jsx
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/client/src/components/pages/participants/participantCourses/index.jsx
  src/client/src/components/pages/participants/participantDates/index.jsx
  src/client/src/components/pages/report/index.jsx
  src/client/src/components/pages/reportResult/index.jsx
Labels: awaiting-review

#235 Edit date and edit intervention
  src/client/src/components/pages/participants/participantCourseDetails/index.jsx
  src/client/src/components/pages/participants/participantDateDetails/index.jsx
  src/server/controllers/index.js
  src/server/controllers/participants.js
Labels: Approved

#238 Last fixing
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/client/src/components/pages/participants/participantDetails/staticData.js
  src/server/database/models/participant.js
Labels: Approved

#240 Lastfixing
  src/client/src/components/pages/courses/addCourses/index.jsx
  src/client/src/components/pages/participants/addParticipant/staticData.js
  src/client/src/components/pages/participants/participantDetails/staticData.js
  src/server/controllers/courses.js
Labels: Approved

#241 Refactoring
  src/client/src/components/pages/courses/addCourses/index.jsx
  src/client/src/components/pages/courses/addCourses/staticData.js
  src/client/src/components/pages/courses/pastoral/staticData.js
  src/client/src/components/pages/courses/viewCourses/index.jsx
  src/client/src/components/pages/participants/participantCourses/index.jsx
  src/server/controllers/managers.js
  src/server/database/models/course.js
Labels: Approved
